### ISSUE TITLE
Can't load files without extensions.

### ISSUE THREAD

**Issue by The-Talik** [satiromarra/vscode-sftp#103]
**Do you read the FAQ?**
- [ X] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When using this extension, I get the following error whenever I try to load a file without an extension.  I do not have this problem with the Natizyskunk version.

Error: Cannot read properties of null (reading '0')
Details:
[2024-08-22 16:45:24] [info] remote ➞ local c:\vscode-sftp\vscode\squanchy\malarkey\dev\changelog
[2024-08-22 16:45:24] [error] TypeError: Cannot read properties of null (reading '0')
	at c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:473032
	at Array.some (<anonymous>)
	at t.isMedia (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:473005)
	at Object.<anonymous> (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:316906)
	at Generator.next (<anonymous>)
	at o (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:316331) 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VSCode Version: 1.92.2
 - Extension Version: 1.18.0

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

[2024-08-22 16:48:23] [debug] grouped-by-host false
[2024-08-22 16:48:23] [debug] grouped-by-context false
[2024-08-22 16:48:23] [info] .env not exists
[2024-08-22 16:48:23] [info] config at c:\vscode-sftp\vscode\sumsum {"remotePath":"/data/sites","uploadOnSave":true,"ignoreRealPath":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"SumSum","host":"sumsum.mezr.com","port":22,"username":"******","password":"******","context":"vscode/sumsum"}
[2024-08-22 16:48:23] [info] config at c:\vscode-sftp\vscode\squanchy {"remotePath":"/data/sites","uploadOnSave":true,"ignoreRealPath":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"Squanchy","host":"squanchy.mezr.com","port":22,"username":"******","password":"******","context":"vscode/squanchy"}
[2024-08-22 16:48:23] [info] config at c:\vscode-sftp\vscode\local {"remotePath":"/data/sites","uploadOnSave":true,"ignoreRealPath":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"Localhost","host":"localhost","port":22,"username":"******","password":"******","context":"vscode/local"}
[2024-08-22 16:48:23] [info] config at c:\vscode-sftp\vscode\malarkey {"remotePath":"/var/www","uploadOnSave":true,"ignoreRealPath":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"Malarkey","host":"malarkeydashboard.com","port":22,"username":"******","password":"******","context":"vscode/malarkey"}
[2024-08-22 16:48:29] [warn] ENOENT: no such file or directory, open 'C:\Users\talik\.ssh\config' load C:\Users\talik\.ssh\config failed
[2024-08-22 16:48:30] [debug] Custom crypto binding not available
[2024-08-22 16:48:30] [debug] Local ident: 'SSH-2.0-ssh2js1.13.0'
[2024-08-22 16:48:30] [debug] Client: Trying squanchy.mezr.com on port 22 ...
[2024-08-22 16:48:30] [debug] Socket connected
[2024-08-22 16:48:30] [debug] Remote ident: 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10'
[2024-08-22 16:48:30] [debug] Outbound: Sending KEXINIT
[2024-08-22 16:48:30] [debug] Inbound: Handshake in progress
[2024-08-22 16:48:30] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ext-info-c
[2024-08-22 16:48:30] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[2024-08-22 16:48:30] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[2024-08-22 16:48:30] [debug] Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[2024-08-22 16:48:30] [debug] Handshake: Host key format: ssh-ed25519
[2024-08-22 16:48:30] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[2024-08-22 16:48:30] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[2024-08-22 16:48:30] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[2024-08-22 16:48:30] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[2024-08-22 16:48:30] [debug] Handshake: C->S MAC: <implicit>
[2024-08-22 16:48:30] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[2024-08-22 16:48:30] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[2024-08-22 16:48:30] [debug] Handshake: S->C MAC: <implicit>
[2024-08-22 16:48:30] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[2024-08-22 16:48:30] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: C->S compression: none
[2024-08-22 16:48:30] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[2024-08-22 16:48:30] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[2024-08-22 16:48:30] [debug] Handshake: S->C compression: none
[2024-08-22 16:48:30] [debug] Outbound: Sending KEXECDH_INIT
[2024-08-22 16:48:31] [debug] Received DH Reply
[2024-08-22 16:48:31] [debug] Host accepted by default (no verification)
[2024-08-22 16:48:31] [debug] Host accepted (verified)
[2024-08-22 16:48:31] [debug] Outbound: Sending NEWKEYS
[2024-08-22 16:48:31] [debug] Inbound: NEWKEYS
[2024-08-22 16:48:31] [debug] Verifying signature ...
[2024-08-22 16:48:31] [debug] Verified signature
[2024-08-22 16:48:31] [debug] Handshake completed
[2024-08-22 16:48:31] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[2024-08-22 16:48:31] [debug] Inbound: Received EXT_INFO
[2024-08-22 16:48:31] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[2024-08-22 16:48:31] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[2024-08-22 16:48:31] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[2024-08-22 16:48:31] [debug] Client: none auth failed
[2024-08-22 16:48:31] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[2024-08-22 16:48:31] [debug] Inbound: Received USERAUTH_SUCCESS
[2024-08-22 16:48:31] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[2024-08-22 16:48:31] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[2024-08-22 16:48:31] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[2024-08-22 16:48:32] [debug] Inbound: REQUEST_SUCCESS
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 242)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com,lsetstat@openssh.com,limits@openssh.com,expand-path@openssh.com)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 31)
[2024-08-22 16:48:32] [debug] SFTP: Outbound: Buffered limits@openssh.com
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received EXTENDED_REPLY (id:0, limits@openssh.com)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 24)
[2024-08-22 16:48:32] [debug] SFTP: Outbound: Buffered OPENDIR
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received HANDLE (id:1)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:32] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 1817)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received NAME (id:2, 15)
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:32] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 32)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received STATUS (id:3, 1, "End of file")
[2024-08-22 16:48:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:32] [debug] SFTP: Outbound: Buffered CLOSE
[2024-08-22 16:48:32] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[2024-08-22 16:48:32] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[2024-08-22 16:48:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 33)
[2024-08-22 16:48:34] [debug] SFTP: Outbound: Buffered OPENDIR
[2024-08-22 16:48:34] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:34] [debug] SFTP: Inbound: Received HANDLE (id:5)
[2024-08-22 16:48:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:34] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:34] [debug] Inbound: CHANNEL_DATA (r:0, 1114)
[2024-08-22 16:48:34] [debug] SFTP: Inbound: Received NAME (id:6, 10)
[2024-08-22 16:48:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:34] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:34] [debug] Inbound: CHANNEL_DATA (r:0, 32)
[2024-08-22 16:48:34] [debug] SFTP: Inbound: Received STATUS (id:7, 1, "End of file")
[2024-08-22 16:48:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:34] [debug] SFTP: Outbound: Buffered CLOSE
[2024-08-22 16:48:34] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[2024-08-22 16:48:34] [debug] SFTP: Inbound: Received STATUS (id:8, 0, "Success")
[2024-08-22 16:48:35] [debug] Outbound: Sending CHANNEL_DATA (r:0, 37)
[2024-08-22 16:48:35] [debug] SFTP: Outbound: Buffered OPENDIR
[2024-08-22 16:48:35] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:35] [debug] SFTP: Inbound: Received HANDLE (id:9)
[2024-08-22 16:48:35] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:35] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:36] [debug] Inbound: CHANNEL_DATA (r:0, 2151)
[2024-08-22 16:48:36] [debug] SFTP: Inbound: Received NAME (id:10, 19)
[2024-08-22 16:48:36] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:36] [debug] SFTP: Outbound: Buffered READDIR
[2024-08-22 16:48:36] [debug] Inbound: CHANNEL_DATA (r:0, 32)
[2024-08-22 16:48:36] [debug] SFTP: Inbound: Received STATUS (id:11, 1, "End of file")
[2024-08-22 16:48:36] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:36] [debug] SFTP: Outbound: Buffered CLOSE
[2024-08-22 16:48:36] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[2024-08-22 16:48:36] [debug] SFTP: Inbound: Received STATUS (id:12, 0, "Success")
[2024-08-22 16:48:38] [trace] run command 'Edit In Local'
[2024-08-22 16:48:38] [trace] handle download file for c:\vscode-sftp\vscode\squanchy\malarkey\dev\changelog
[2024-08-22 16:48:38] [debug] Outbound: Sending CHANNEL_DATA (r:0, 47)
[2024-08-22 16:48:38] [debug] SFTP: Outbound: Buffered LSTAT
[2024-08-22 16:48:38] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[2024-08-22 16:48:38] [debug] SFTP: Inbound: Received ATTRS (id:13)
[2024-08-22 16:48:38] [debug] Outbound: Sending CHANNEL_DATA (r:0, 59)
[2024-08-22 16:48:38] [debug] SFTP: Outbound: Buffered OPEN
[2024-08-22 16:48:38] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:38] [debug] SFTP: Inbound: Received HANDLE (id:14)
[2024-08-22 16:48:38] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[2024-08-22 16:48:38] [debug] SFTP: Outbound: Buffered READ
[2024-08-22 16:48:38] [debug] Inbound: CHANNEL_DATA (r:0, 6884)
[2024-08-22 16:48:38] [debug] SFTP: Inbound: Received DATA (id:15, 6871)
[2024-08-22 16:48:38] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[2024-08-22 16:48:38] [debug] SFTP: Outbound: Buffered READ
[2024-08-22 16:48:38] [debug] Inbound: CHANNEL_DATA (r:0, 32)
[2024-08-22 16:48:38] [debug] SFTP: Inbound: Received STATUS (id:16, 1, "End of file")
[2024-08-22 16:48:38] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[2024-08-22 16:48:38] [debug] SFTP: Outbound: Buffered CLOSE
[2024-08-22 16:48:38] [info] remote ➞ local c:\vscode-sftp\vscode\squanchy\malarkey\dev\changelog
[2024-08-22 16:48:38] [error] TypeError: Cannot read properties of null (reading '0')
	at c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:473032
	at Array.some (<anonymous>)
	at t.isMedia (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:473005)
	at Object.<anonymous> (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:316906)
	at Generator.next (<anonymous>)
	at o (c:\Users\talik\.vscode\extensions\satiromarra.code-sftp-1.18.1\dist\extension.js:2:316331) 
[2024-08-22 16:48:38] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[2024-08-22 16:48:38] [debug] SFTP: Inbound: Received STATUS (id:17, 0, "Success")
[2024-08-22 16:49:02] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[2024-08-22 16:49:02] [debug] Inbound: Received REQUEST_FAILURE

**Comment by snouker** [comment]
I encountered this issue and successfully reproduced it.
Also,#96 should be the same as this issue.
