### ISSUE TITLE
command 'sftp.remoteExplorer.refresh' already exists

### ISSUE THREAD

**Issue by myfender** [satiromarra/vscode-sftp#69]
Good morning, when I open vscode I have this error: command 'sftp.remoteExplorer.refresh' already exists.
this is the detail:

[2023-07-03 07:48:02] [error] Error: command 'sftp.remoteExplorer.refresh' already exists
    at e.ExtHostCommands.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:129137)
    at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:23413)
    at t.registerCommand (/Users/iloiacono/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:440071)
    at new t.default (/Users/iloiacono/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:453993)
    at /Users/iloiacono/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:413723
    at Generator.next (<anonymous>)
    at o (/Users/iloiacono/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:412808)

**Comment by myfender** [comment]
Sorry, my mistake, I had 2 extensions SFTP active. Sorted
