### ISSUE TITLE
Error: Packet length 1349281121 exceeds max length of 262144

### ISSUE THREAD

**Issue by 4044ever** [satiromarra/vscode-sftp#95]
VS Code on Windows 10

sftp.json
```
    {
        "name": "nosite-sftp",
        "host": "146.2.222.52",
        "protocol": "sftp",
        "port": 22,
        "username": "root",
        "privateKeyPath": "ssh-key-2024-01-31.key",
        "remotePath": "/var/www/nosite/htdocs",
        "uploadOnSave": false
       }
```

From the log:

```
[2024-02-14 22:22:26] [info] Section for '146.2.222.52' found with Host or Match
[2024-02-14 22:22:31] [error] Error: Packet length 1349281121 exceeds max length of 262144
	at doFatalSFTPError (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\SFTP.js:2713:15)
	at SFTP.push (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\SFTP.js:220:18)
	at CHANNEL_DATA (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\client.js:587:23)
	at 94 (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\handlers.misc.js:930:16)
	at Protocol.onPayload (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\Protocol.js:2052:10)
	at AESGCMDecipherNative.decrypt (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\Protocol.js:2021:25)
	at Protocol.parse (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\protocol\Protocol.js:306:16)
	at Socket.<anonymous> (c:\Users\tina_home\.vscode\extensions\satiromarra.code-sftp-1.18.1\node_modules\ssh2\lib\client.js:775:21)
	at Socket.emit (node:events:514:28)
	at Socket.emit (node:domain:489:12)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Socket.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) 
```

Any hints?

**Comment by satiromarra** [comment]
@4044ever  The error is typically caused by message printed from startup script .profile, .bashrc... 
https://stackoverflow.com/questions/33409233/getting-received-too-large-sftp-packet-when-logging-in-with-root-using-winscp
