### ISSUE TITLE
Autoupload on save broken in 1.89

### ISSUE THREAD

**Issue by shynekomaid** [satiromarra/vscode-sftp#99]
_Yes, I read all shitty guides._

When I use "Upload" in right-click menu - upload work nice:
```
[2024-05-08 13:42:45] [info] Using profile: local
[2024-05-08 13:42:59] [info] Using profile: proxy2
[2024-05-08 13:42:59] [info] uploading temp file: /scr/www/web/templates/main.php.new
[2024-05-08 13:42:59] [info] moving from: /scr/www/web/templates/main.php.new to: /scr/www/web/templates/main.php
[2024-05-08 13:43:00] [info] local ➞ remote /home/shyneko/Documents/Github/SOLAR_CK_WEB/web/templates/main.php
```

But when save (with upload on save) I get error:
```
[2024-05-08 13:40:37] [info] [file-save] /run/media/shyneko/28b2a378-11ad-4126-a6e6-4583c2195cac/Github/SOLAR_CK_WEB/web/templates/main.php
[2024-05-08 13:40:37] [error] Error: Config Not Found. (file:///run/media/shyneko/28b2a378-11ad-4126-a6e6-4583c2195cac/Github/SOLAR_CK_WEB/web/templates/main.php)
	at l (/home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:416739)
	at /home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:417103
	at Generator.next (<anonymous>)
	at /home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:416475
	at new Promise (<anonymous>)
	at n (/home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:416220)
	at /home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:417042
	at /home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:447663
	at Generator.next (<anonymous>)
	at o (/home/shyneko/.vscode/extensions/satiromarra.code-sftp-1.18.1/dist/extension.js:2:446644) download /run/media/shyneko/28b2a378-11ad-4126-a6e6-4583c2195cac/Github/SOLAR_CK_WEB/web/templates/main.php
```

My huge config:
```
[
    {
        "name": "SOLAR web",
        "protocol": "sftp",
        "context": "web",
        "uploadOnSave": true,
        "downloadOnOpen": false,
        "useTempFile": true,
        "openSsh": true,
        "remotePath": "/scr/www/web",
        "defaultProfile": "proxy2",
        "profiles": {
            "proxy": {
                "name": "Debug Proxied",
                "host": "${ENV:SERVER1_HOST}",
                "username": "${ENV:SERVER1_USER}",
                "password": "${ENV:SERVER1_PASS}",
                "port": 22022
            },
            "local": {
                "name": "Debug Local",
                "host": "${ENV:SERVER2_HOST}",
                "username": "${ENV:SERVER2_USER}",
                "password": "${ENV:SERVER2_PASS}",
                "port": 22
            },
            "proxy2": {
                "name": "Debug Local",
                "host": "${ENV:SERVER3_HOST}",
                "username": "${ENV:SERVER3_USER}",
                "password": "${ENV:SERVER3_PASS}",
                "port": 40001
            }
        }
    },
    {
        "name": "SOLAR nginx dir",
        "protocol": "sftp",
        "context": "backup/nginx/nginx",
        "uploadOnSave": true,
        "downloadOnOpen": false,
        "useTempFile": true,
        "openSsh": true,
        "remotePath": "/etc/nginx",
        "defaultProfile": "local",
        "profiles": {
            "proxy": {
                "name": "Debug Proxied",
                "host": "${ENV:SERVER1_HOST}",
                "username": "${ENV:SERVER1_USER}",
                "password": "${ENV:SERVER1_PASS}",
                "port": 22022
            },
            "local": {
                "name": "Debug Local",
                "host": "${ENV:SERVER2_HOST}",
                "username": "${ENV:SERVER2_USER}",
                "password": "${ENV:SERVER2_PASS}",
                "port": 22
            }
        }
    },
    {
        "name": "SOLAR nginx conf",
        "protocol": "sftp",
        "uploadOnSave": true,
        "downloadOnOpen": false,
        "useTempFile": true,
        "openSsh": true,
        "remotePath": "/scr/www/config",
        "defaultProfile": "local",
        "profiles": {
            "proxy": {
                "name": "Debug Proxied",
                "host": "${ENV:SERVER1_HOST}",
                "username": "${ENV:SERVER1_USER}",
                "password": "${ENV:SERVER1_PASS}",
                "port": 22022
            },
            "local": {
                "name": "Debug Local",
                "host": "${ENV:SERVER2_HOST}",
                "username": "${ENV:SERVER2_USER}",
                "password": "${ENV:SERVER2_PASS}",
                "port": 22
            }
        }
    }
]
```

&

```
shyneko@shyneko-solus ~ $ uname -a
Linux shyneko-solus 6.8.8-288.current #1 SMP PREEMPT_DYNAMIC 0 x86_64 GNU/Linux
shyneko@shyneko-solus ~ $ lsb_release -a
LSB Version:    1.4
Distributor ID: Solus
Description:    Solus
Release:        4.5
Codename:       resilience
shyneko@shyneko-solus ~ $
```

**Comment by lizeshakya** [comment]
For anyone receiving the same issue, 

adding following code in sftp.json resolved the issue

`"ignoreRealPath":true`

The solution was retrieved from the similar issue in #83 [comment](https://github.com/satiromarra/vscode-sftp/issues/83#issuecomment-1699887752).
